In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Airbnb_Open_Data.csv")

/var/folders/c0/fkwzzmb92yldm18l2b0gx5wh0000gn/T/ipykernel_18033/180275767.py:1: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Airbnb_Open_Data.csv")

In [3]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [4]:
data.columns  #to check columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(14)
memory usage: 20.4+ MB

In [6]:
# i can see some enomally, license has no almost no data in it, only 2 non-null values

In [7]:
data["license"]

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
102594    NaN
102595    NaN
102596    NaN
102597    NaN
102598    NaN
Name: license, Length: 102599, dtype: str

In [8]:
data.shape

(102599, 26)

In [9]:
# dropping The liscense column
data = data.drop(columns = ["license"])

In [10]:
data.info() # checking whether the license has dropped or not, or we can use inplace = True.

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
dtypes: float64(9), int64(2), object(1), str(13)
memory usage: 19.6+ MB

In [11]:
data['house_rules'].value_counts()

house_rules
#NAME?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2712
House Rules 1. Check-in is 4 pm local time. If the unit is ready earlier, we’ll let you know. Check-out is normally 11 am local time, but we’d be happy to extend it as long as we don’t have a cleaning scheduled. Just let us know.  2. All bookings require a security deposit of at least $300, which will be refunded within 7 days of your check-out. 3. For security measures we require all guests to provide proof of identification through ID verification on our own website. In order to check in we'll need a photo of your ID.  4. Our cancellation policy is as shown on our ad and defined by the site you are booking through.  5. Don’t let $300 go up in smoke. There's no smoking allowed in any Flatbook and a $300 fine for breaking this rule.  6. Unfortunately we don’t allow pets in any of our apartments. 7. Unless you’re staying in one of our specialty apartments, we don’t allow parties or excessive noise. 8. If we find the place very messy, we have to charge an extra $40 for every extra hour o     904
Please remember that this is a residential building. The building rules, apartment occupancy restrictions and the year-round tenants must be respected.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      881
No Smoking No Pets                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           814
Please remember that this is a residential building. The building rules, apartment occupancy restrictions and the year-round tenants must be respected.  Parties, pets and smoking are not allowed under any circumstances and incur significant fees.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       552
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
18 star treatment is given and expected.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
- Quiet time after 24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
15 guest maximum.  Smoking isn't permitted and unfortunately neither are pets. Sorry.   Quiet hours 9p-8a.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
15 nights minimum stay No pets at any time No smoking Please be mindful of the furniture and personal belongings, it was all furnished with designer pieces and hard to replace things.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
16 nights minimum stay, no smoking or pets.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
Name: count, Length: 1976, dtype: int64

In [12]:
data['reviews per month'].value_counts()

reviews per month
0.03     1666
0.05     1490
1.00     1455
0.04     1270
0.09     1269
         ...
26.11       1
7.80        1
7.73        1
24.49       1
33.08       1
Name: count, Length: 1016, dtype: int64

In [14]:
new_clns = []
for i in data.columns:
    new_clns.append(i.lower())

In [15]:
# making everything Lower Case.

In [16]:
data['reviews per month']

0         0.21
1         0.38
2          NaN
3         4.64
4         0.10
          ...
102594     NaN
102595    0.02
102596     NaN
102597    0.10
102598     NaN
Name: reviews per month, Length: 102599, dtype: float64

In [17]:
nmd = data.copy()

In [18]:
nmd

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and..."
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN

In [19]:
nmd.columns = new_clns

In [20]:
nmd.columns

Index(['id', 'name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules'],
      dtype='str')

In [21]:
nmd['name'].value_counts()

name
Home away from home                              33
Hillside Hotel                                   30
Water View King Bed Hotel Room                   30
Brooklyn Apartment                               27
New york Multi-unit building                     27
                                                 ..
Bear(B)                                           1
Cozy 1bd in Kensington                            1
Elmhurst 1st Fl Rightl Bedroom                    1
Elmhurst 1st Floor BR w/ Pvt. Bath&Balcony        1
Parisian Style Apartment in Heart of Brooklyn     1
Name: count, Length: 61281, dtype: int64

In [22]:
nmd['name']

0                       Clean & quiet apt home by the park
1                                    Skylit Midtown Castle
2                      THE VILLAGE OF HARLEM....NEW YORK !
3                                                      NaN
4         Entire Apt: Spacious Studio/Loft by central park
                                ...
102594                          Spare room in Williamsburg
102595                       Best Location near Columbia U
102596                      Comfy, bright room in Brooklyn
102597                    Big Studio-One Stop from Midtown
102598                                585 sf Luxury Studio
Name: name, Length: 102599, dtype: str

In [23]:
nmd['house_rules'].value_counts()

house_rules
#NAME?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2712
House Rules 1. Check-in is 4 pm local time. If the unit is ready earlier, we’ll let you know. Check-out is normally 11 am local time, but we’d be happy to extend it as long as we don’t have a cleaning scheduled. Just let us know.  2. All bookings require a security deposit of at least $300, which will be refunded within 7 days of your check-out. 3. For security measures we require all guests to provide proof of identification through ID verification on our own website. In order to check in we'll need a photo of your ID.  4. Our cancellation policy is as shown on our ad and defined by the site you are booking through.  5. Don’t let $300 go up in smoke. There's no smoking allowed in any Flatbook and a $300 fine for breaking this rule.  6. Unfortunately we don’t allow pets in any of our apartments. 7. Unless you’re staying in one of our specialty apartments, we don’t allow parties or excessive noise. 8. If we find the place very messy, we have to charge an extra $40 for every extra hour o     904
Please remember that this is a residential building. The building rules, apartment occupancy restrictions and the year-round tenants must be respected.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      881
No Smoking No Pets                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           814
Please remember that this is a residential building. The building rules, apartment occupancy restrictions and the year-round tenants must be respected.  Parties, pets and smoking are not allowed under any circumstances and incur significant fees.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       552
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
18 star treatment is given and expected.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
- Quiet time after 24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
15 guest maximum.  Smoking isn't permitted and unfortunately neither are pets. Sorry.   Quiet hours 9p-8a.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
15 nights minimum stay No pets at any time No smoking Please be mindful of the furniture and personal belongings, it was all furnished with designer pieces and hard to replace things.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
16 nights minimum stay, no smoking or pets.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
Name: count, Length: 1976, dtype: int64

In [24]:
nmd.isna().sum()

id                                    0
name                                250
host id                               0
host_identity_verified              289
host name                           406
neighbourhood group                  29
neighbourhood                        16
lat                                   8
long                                  8
country                             532
country code                        131
instant_bookable                    105
cancellation_policy                  76
room type                             0
construction year                   214
price                               247
service fee                         273
minimum nights                      409
number of reviews                   183
last review                       15893
reviews per month                 15879
review rate number                  326
calculated host listings count      319
availability 365                    448
house_rules                       52131
dtype: int64

In [25]:
nmd['lat']

0         40.64749
1         40.75362
2         40.80902
3         40.68514
4         40.79851
            ...
102594    40.70862
102595    40.80460
102596    40.67505
102597    40.74989
102598    40.76807
Name: lat, Length: 102599, dtype: float64

In [26]:
nmd['long']

0        -73.97237
1        -73.98377
2        -73.94190
3        -73.95976
4        -73.94399
            ...
102594   -73.94651
102595   -73.96545
102596   -73.98045
102597   -73.93777
102598   -73.98342
Name: long, Length: 102599, dtype: float64

In [27]:
nmd['country']

0         United States
1         United States
2         United States
3         United States
4         United States
              ...
102594    United States
102595    United States
102596    United States
102597    United States
102598    United States
Name: country, Length: 102599, dtype: str

In [28]:
nmd.duplicated().sum()

541

In [29]:
nmd.duplicated().value_counts()

False    102058
True        541
Name: count, dtype: int64

In [30]:
# there are 541 duplicates value in the data.

In [31]:
# Show every row that is a complete duplicate of another row
all_duplicates = nmd[nmd.duplicated(keep=False)]

In [32]:
all_duplicates

,id,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
9098,6026161,Upper East Side 2 bedroom- close to Hospitals-,65193709566,verified,Juliana,Manhattan,Upper East Side,40.76222,-73.96030,United States,...,$105,$21,30.0,2.0,6/8/2019,0.21,3.0,34.0,157.0,NaN
9099,6026714,Close to East Side Hospitals- Modern 2 Bedroom...,31072202372,verified,Juliana,Manhattan,Upper East Side,40.76249,-73.96217,United States,...,$285,$57,30.0,6.0,1/31/2019,0.14,3.0,34.0,67.0,"The quieter the better, but otherwise make you..."
9100,6027266,ACADIA Spacious 2 Bedroom Apt - Close to Hospi...,95854111798,verified,Juliana,Manhattan,Upper East Side,40.76021,-73.96157,United States,...,$586,$117,30.0,10.0,11/18/2018,0.22,5.0,34.0,211.0,No Smoking No Pets
9101,6027818,*ENCHANTMENT* Upper East Side 2 bedroom- Sunny!,73401481508,unconfirmed,Juliana,Manhattan,Upper East Side,40.76244,-73.96031,United States,...,$539,$108,30.0,9.0,9/30/2018,0.20,5.0,34.0,411.0,Please treat it as it were your own home and b...
9102,6028371,*JAMES* Amazing Spacious 2 Bedroom- Bright!,37678424985,verified,Juliana,Manhattan,Upper East Side,40.76035,-73.96133,United States,...,$806,$161,30.0,8.0,6/11/2019,0.27,4.0,34.0,411.0,Be courteous and respectful to people in the h...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN

In [33]:
# what i am seeing is the duplicated values are somewhat necessary.!

In [34]:
nmd['price']

0           $966
1           $142
2           $620
3           $368
4           $204
           ...
102594      $844
102595      $837
102596      $988
102597      $546
102598    $1,032
Name: price, Length: 102599, dtype: str

In [35]:
data['price'] = data['price'].str.replace('$', '', regex=False)

In [36]:
data['price']

0           966
1           142
2           620
3           368
4           204
           ...
102594      844
102595      837
102596      988
102597      546
102598    1,032
Name: price, Length: 102599, dtype: str

In [37]:
# also we need to remove the commas as well to finally convert it into a integer
nmd['price'] = nmd['price'].str.replace(',','',regex=False)

In [38]:
nmd['price'] #succesfully remove.

0          $966
1          $142
2          $620
3          $368
4          $204
           ...
102594     $844
102595     $837
102596     $988
102597     $546
102598    $1032
Name: price, Length: 102599, dtype: str

In [39]:
print(nmd['price'].dtype) # its string dat type. now converting it into an integer

str

In [40]:
nmd['price'] = nmd['price'].astype(int)

ValueError: invalid literal for int() with base 10: '$966 '

In [41]:
nmd['price'].isna().sum() # so there are 247 null values to it!

247

In [42]:
# Returns only the rows where 'price' is missing
missing_price = nmd[nmd['price'].isna()][['id', 'name', 'price']]

In [43]:
missing_price

              id                                               name price
147      1082524                            Retreat in Williamsburg   NaN
148      1083076                                            NYC Zen   NaN
210      1117319                Private Garden Apt • New Renovation   NaN
211      1117871  Modern comfort in art infused landmark Brownstone   NaN
212      1118424                NOHO/EAST VILLAGE, PRIVATE 1/2 BATH   NaN
...          ...                                                ...   ...
102046  57361342             Sunny budget friendly room in Bushwick   NaN
102047  57361894            Cozy Apartment on Bedford Ave, Brooklyn   NaN
102048  57362446                Your 1 bedroom home away from home!   NaN
102049  57362999  MASTER Cozy Bedroom Queen size 2 blocks Timesq...   NaN
102050  57363551        Sunny Brownstone Studio in BedStuy Brooklyn   NaN

[247 rows x 3 columns]

In [44]:
pd.set_option('display.max_rows', None)
missing_price

              id                                               name price
147      1082524                            Retreat in Williamsburg   NaN
148      1083076                                            NYC Zen   NaN
210      1117319                Private Garden Apt • New Renovation   NaN
211      1117871  Modern comfort in art infused landmark Brownstone   NaN
212      1118424                NOHO/EAST VILLAGE, PRIVATE 1/2 BATH   NaN
213      1118976                       Sleek & Comfortable Soho Apt   NaN
403      1223913                  Cozy and Bright One Bedroom in BK   NaN
404      1224465      Forest Hills Apt minutes to midtown Manhattan   NaN
405      1225018                Spacious West Village 1 b/room King   NaN
516      1286323                  Comfort at Crossroads of Downtown   NaN
517      1286875                "The Oasis" on Bedford Williamsburg   NaN
5882     4249965                  Two bedroom in Prime East Village   NaN
5883     4250517                    1 Bedroom in Greenwich Village!   NaN
5884     4251069  LG GARDEN Apt ON Sunset Park,  on41ST near 6th...   NaN
5885     4251622       New Apt near Central Park, Broadway, Museums   NaN
5886     4252174                Cozy 1BD on historic Stuyvesant St.   NaN
5908     4264324                                   Wonderful Willi!   NaN
5909     4264877                          Upper East Side 1-Bedroom   NaN
5910     4265429                     Big Room with Private Bathroom   NaN
5911     4265981             Big Sunny Room in Apartment With Views   NaN
5979     4303538                Beautiful Railroad Style Apartment!   NaN
5980     4304090                       Spacious 1Br in East Village   NaN
5981     4304642   Room in Bushwick Brooklyn NYC, LG KITCHEN & YARD   NaN
5982     4305195  Child-friendly 2BR w/ Yard access and Free Par...   NaN
5983     4305747                 specious 1bd apt on Saint Marks Pl   NaN
6054     4344960     Studio-Private Entrance /Bath/Kitchen Near JFK   NaN
6055     4345513                Prime East Village One Bedroom Apt!   NaN
6056     4346065  1st Time/Solo/Duo Travelers!Charming Studio Sh...   NaN
6057     4346617                                HOME AWAY FROM HOME   NaN
13460    8435294                  Victorian Home, Welcoming Comfort   NaN
13461    8435846                         Cozy apartment in Brooklyn   NaN
13462    8436399                        Beautiful Bedford apartment   NaN
13463    8436951                Well Equipped One-Bedroom Apartment   NaN
13464    8437503                               Williamsburg Getaway   NaN
13465    8438056                    Charming Williamsburg apartment   NaN
13466    8438608                     Clean room in a nice apartment   NaN
13467    8439160                               Deluxe Brooklyn Loft   NaN
13501    8457938                      Futon in Brooklyn near subway   NaN
13502    8458491                Great room*City View*Huge roofdeck*   NaN
13503    8459043                  Cozy 1-Bd, Bushwick (L/M/J train)   NaN
13504    8459595                   East Village Bedroom w/Roof Deck   NaN
13505    8460148    Bright, Spacious Brooklyn Space w/ Private Bath   NaN
13506    8460700                            Spacious and cozy room!   NaN
13507    8461252                  Studio next to Washington Sq Park   NaN
13508    8461804                                  Midtown Manhattan   NaN
13509    8462357                UWS large, Elev./Security 1-Bedroom   NaN
13510    8462909                 Sunny One Bedroom in Crown Heights   NaN
13511    8463461  Peaceful Artist Bedroom—Just 30 Min to Manhattan!   NaN
13512    8464014                 Newly renovated, 1.5 bdr  SoHo apt   NaN
13547    8483344                          2 bedroom Upper east side   NaN
13548    8483896  Artsy/Neat 1 Bedroom Apartment in the heart of...   NaN
13549    8484449                         Cute bedroom in Chinatown,   NaN
13550    8485001                1 Bedroom in HUGE Full Floored Apt.   NaN
13551    8485553                Family Room/Kitchen/Shared Bathroom   NaN
13552    8486106                          1 Bedroom in East Village   NaN
13595    8509855             Brooklyn apartment 20 min to Manhattan   NaN
13596    8510407  Spacious railroad style 3 bedroom apt in Manha...   NaN
13597    8510959                 Resort-like living in Williamsburg   NaN
13598    8511511       Sunny Cozy Private Room in East Williamsburg   NaN
13599    8512064        Sunny, Spacious Private BR in East Village!   NaN
13600    8512616                 Great Affordable Room In Manhattan   NaN
13601    8513168                  Gorgeous and Sunlit 1 BR 31/1-3/1   NaN
18084   10989129                             nice room in bedstuy G   NaN
18085   10989682   Gorgeous Sunset-facing Carroll Gardens 1 Bedroom   NaN
24258   14399029                             Rainbow Guesthouse 1-6   NaN
24259   14399582  Modern 3 Bedroom 2 BATH! 18 min to Times Sq+More!   NaN
24260   14400134                           East Williamsburg Studio   NaN
24261   14400686             Bohemian Room in NYC at Great Location   NaN
24262   14401239     Charming Luxury Apartment in Central Manhattan   NaN
24263   14401791       Comfortable studio in heart of LES/Chinatown   NaN
24264   14402343                Beautiful 2 Bedroom Lower East Side   NaN
24265   14402896                      Private Prospect Heights room   NaN
24266   14403448    Large+Amazing 2BR ( Flex)-Upper East Side-E89th   NaN
24326   14436586  30+ Day Stay -Cute Small House by a Beautiful ...   NaN
24327   14437138     Habitación ubicada céntricamente en la ciudad.   NaN
24328   14437690    Sun filled 1 bedroom, 20 minutes from Manhattan   NaN
24329   14438243        Artist's X-Large 2 Bedroom Loft w/King Bed.   NaN
24330   14438795                                Cozy room in Nolita   NaN
24331   14439347  30+Day: Fun 3 Bedroom (kids Favorite) Home by ...   NaN
24332   14439900  30+Day Stay:Designer Sky Beautiful Loft (1000 sf)   NaN
24375   14463649      Upper west side - perfect feel at home place.   NaN
24376   14464201                         Scenic Brooklyn townhouse.   NaN
24377   14464753                2 bed / 2.5 bath with outdoor space   NaN
24378   14465305   Comfortable,3 bedroom, 2bath home away from home   NaN
24379   14465858   Charming apartment (sleeps 2-4) in UES Manhattan   NaN
24380   14466410                    Modern Spacious and Sunny Place   NaN
24381   14466962                                                NaN   NaN
24382   14467515                  Artist's loft / Room / Greenpoint   NaN
24383   14468067                                                NaN   NaN
24430   14494025             Garden Master Bedroom in Crown Heights   NaN
24431   14494577  Beautiful Williamsburg Loft 1/2 Block from Sub...   NaN
24432   14495130     JFK 10 & LGA 15 minutes Single bed in the room   NaN
24433   14495682                                                NaN   NaN
24434   14496234                           Cute, sunny room in NYC!   NaN
24435   14496787                Modern and Private Duplex Apartment   NaN
30933   18085632  Beautiful red-brick bedroom in prime East Village   NaN
30934   18086184                                Home away from home   NaN
30935   18086737       Private Bedroom-Upper East Side-Central Park   NaN
36794   21322662  Private room 3 min walking to J train(female o...   NaN
36795   21323215             Greenpoint Apt with a wonderful view !   NaN
36796   21323767  Romantic space at the Upper East side of Manha...   NaN
36797   21324319   Garden apartment in historic Brooklyn townhouse.   NaN
36853   21355248                   Upper East Side Family Apartment   NaN
36854   21355800  Luxury - Jr. 1 Br/High Fl- Rooftop Terrace Access   NaN
36855   21356353  NYC Central Park Lux Hotel w/ Brfast & Dinner ...   NaN
36919   21391700  Home to LGA airport near Manhattan, JFk, Astoria.   NaN
36920   21392252                                         Sams place   NaN
36921   21392804                         Very comfortable and clean   NaN
37037   21456871         Great New York -  Private or shared room 2   NaN
37038   21457423    BEST LOCATION!! Whole Apartment with Backyard!!   NaN
37039   21457976           Serene & clean stay in a luxury building   NaN
37040   21458528             East Village Sublet multi month please   NaN
37041   21459080              Artistic Studio Apt, Private Entrance   NaN
37042   21459633  Beautiful apartment next to Central Park & The...   NaN
37043   21460185  Modern 1BR Astoria, espresso maker, 5 min 2 train   NaN
37169   21529775          Private bed in a huge apartment! Him-1R-1   NaN
37170   21530327               Private Bedroom in Bushwick Him-1R-2   NaN
37171   21530879               Amazing Bedroom in Brooklyn Him-1R-3   NaN
37172   21531432  Private Bedroom in the heart of Bushwick Him-1R-4   NaN
37173   21531984               Gorgeous Bedroom on Himrod! Him-1R-5   NaN
37174   21532536    East 82nd Street, Upper East Side/Yorkville 1bd   NaN
37175   21533089         New gorgeous garden view spacious 1BR flat   NaN
37176   21533641            One block from subway: bed for traveler   NaN
37263   21581691          New  Renovation cozy sweet apartment｡3 FL   NaN
37264   21582243     ♀ New Sunny Furnished Room near Express Subway   NaN
37265   21582796     ♀ New Large Sunny Room close to  Express Train   NaN
37266   21583348                  Hip and minimal neighborhood loft   NaN
37267   21583900  New Large 3bd furnished space. Walk to Fast Su...   NaN
37268   21584452        1 bedroom apartment across the Central Park   NaN
37269   21585005  Sunny and cozy room 10 minutes from Times Sq.61F3   NaN
37270   21585557                Quiet, light-filled, Soho apartment   NaN
41155   23731243               Murray Hill Jewel With Outdoor Space   NaN
41156   23731795  Half a block from the train! my private cozy room   NaN
41157   23732347                Room for rent from March to August.   NaN
41158   23732899                                   comfortable cozy   NaN
41159   23733452                          Cozy room next to subway!   NaN
41160   23734004                       Forest Sanctuary in Bushwick   NaN
51214   29286828  Newly renovated modern & private studio apartment   NaN
51215   29287381         Awesome Brightness Room Close to Downtown!   NaN
51216   29287933      Vibrant Loft Apartment with *Private Terrace*   NaN
65609   37237187        Family haven in trendy Greenpoint, Brooklyn   NaN
65610   37237739       A+ Location Classic Queen Studio (Queen Bed)   NaN
65611   37238291         Midtown West One Bedroom near Times Square   NaN
65612   37238844                            Gloria’s Brooklyn Space   NaN
65613   37239396                   Amazing Greenwich Village w pool   NaN
65641   37254860   Bushwick HD TV room 19 min to Manhattan 2FL -#88   NaN
65642   37255413        Manhattan PRIME Location. Luxury apartment.   NaN
65643   37255965                               Big Private Room # 3   NaN
65644   37256517  Live in best part of Williamsburg waterfront -...   NaN
65645   37257070  Spacious Lower East Side 1 BR w/ dedicated office   NaN
65646   37257622             Bright Greenwich village 2-room studio   NaN
65647   37258174     Prospect park HD TV room on Franklin Ave -#197   NaN
65648   37258726  2 Beds/Queen & Full Beautiful Room 40 minsT.Sq...   NaN
65763   37322241                       Spread Luv the Brooklyn Way!   NaN
65764   37322793  New location/ Bushwick BK / Big Room w TV in Bsmt   NaN
65765   37323346            Specious Studio in the Heart of midtown   NaN
65766   37323898       Enormous, bright, and chic Williamsburg loft   NaN
65767   37324450                 Beautiful Renovated Apartment NYC.   NaN
65768   37325002                Sunny, spacious 1 Bedroom apartment   NaN
65769   37325555             UNBEATABLE VIEW/SUNNY ROOM/BIG WINDOWS   NaN
65770   37326107                                        Comfy Rooms   NaN
65771   37326659     Sunnysid -Locals' favorite neighbor for living   NaN
65772   37327212     Easy access to Manhattan : Nice Condition room   NaN
65773   37327764             Bushwick private apartment in Brooklyn   NaN
65852   37371396                      Luxurious Suite Grand Central   NaN
65853   37371948                        Renovated  modern 1 bedroom   NaN
65854   37372500                     Water View King Bed Hotel Room   NaN
65855   37373053        Spacious Newly Renovated Brooklyn Apartment   NaN
65856   37373605  Safe Chelsea block by Hudson Yards & many Subways   NaN
65857   37374157           Beautiful Apartment with Manhattan view.   NaN
65858   37374709      1 Bedroom Elevator Building Apartment in SoHo   NaN
65859   37375262                       Hotel Hendricks, Deluxe King   NaN
65860   37375814             Luminous Beautiful West Village Studio   NaN
65861   37376366         Clean, sunny 2BR in Brooklyn's Nicest Area   NaN
65950   37425521                       Stylish and Cozy One Bedroom   NaN
65951   37426073  Large sunny 1+ BR apartment, close to subway &...   NaN
65952   37426626       Two Bedroom Near Columbia U/Morningside Park   NaN
65953   37427178      Spacious, quiet 1 br apt in beautiful Inwood!   NaN
65954   37427730       Popular Room !! Apartment in jackson heights   NaN
65955   37428283          Spacious one bedroom in midtown Manhattan   NaN
65956   37428835                 Private Room in Beautiful Soho NYC   NaN
65957   37429387                     Awesome room |Private BATHROOM   NaN
65958   37429939         VarandaBliss getaway minutes from the city   NaN
65959   37430492  Stunning Midtown East 1 Bed w/ Gym, Rooftop #6135   NaN
65960   37431044     Bright studio, fully-furnished, great location   NaN
65961   37431596  Hotel Indigo LES Studio Suite with Skyline Ter...   NaN
65962   37432149                       PRIVATE Bathroom in woodside   NaN
65963   37432701  Double Room w Private Deck Clinton Hill Best Area   NaN
65964   37433253         Luxury Furnished 1 BR UWS Apt w W/D & Deck   NaN
66028   37468600      Extra large and quiet room in a creative nest   NaN
66029   37469153       Private Room w/ a backyard close to the City   NaN
66030   37469705                      Sunny, Spacious, Jungle Oasis   NaN
66031   37470257                Wall St | Wally St Room + Manhattan   NaN
66032   37470810    Private apt, charming, safe, near Prospect Park   NaN
66033   37471362                           Private room airy modern   NaN
66034   37471914                 Stylish Apt in Heart of Ft. Greene   NaN
66035   37472467  Artsy Small 2 Bedroom PRIME EAST VILLAGE LOCATION   NaN
66036   37473019    Guest suite in owner-occupied private residence   NaN
66037   37473571                Nice 1bedroom Next to Prospect Park   NaN
66038   37474123       Near the station! Easy apartment in woodside   NaN
66107   37512232                Live in Harlem close to Columbia U!   NaN
66108   37512784   Beautiful, cozy, Penthouse Studio in Astoria/LIC   NaN
66109   37513337                Modern designed room near B/C train   NaN
66110   37513889    1 Brd Apt, Active Area, 1 Train Stop From  NYC.   NaN
66111   37514441                         Grand Brooklyn Experience!   NaN
66112   37514994  Entire 2 bedroom apt in the heart of East Village   NaN
66113   37515546   Smile Ridgewood — Bedroom + Private Living Room!   NaN
66114   37516098  Good location♪ 2min from station! 5Lines u can...   NaN
66115   37516651  Modern, Designer 1 bedroom prime Brooklyn loca...   NaN
66116   37517203                  Bright & Modern Studio in Chelsea   NaN
66117   37517755          Manhattan Studio Apartment: 2 Adults $125   NaN
79785   45066592       New tidy  room attached by PRIVATE FULL BATH   NaN
79786   45067144                           Charming, small and cozy   NaN
79787   45067696        BEAUTIFUL BROWNSTONE STUDIO IN SOUTH HARLEM   NaN
79788   45068248      Beautiful 1 bedroom Apartment in Midtown East   NaN
79789   45068801                 Cozy Room Minutes To Manhattan. #2   NaN
87906   49551820                             nice room in bedstuy G   NaN
87907   49552372   Gorgeous Sunset-facing Carroll Gardens 1 Bedroom   NaN
97710   54966569              1 Bedroom off Columbus fit for a King   NaN
97711   54967121     Beautiful S Williamsburg 1 Bdrm near G,L,J,M,Z   NaN
97712   54967674  Sunny Master Bedroom In Prime Williamsburg 30 ...   NaN
97713   54968226             Spacious & Sunny Master w Private Bath   NaN
97714   54968778        Fort Greene two bedroom, quiet and peaceful   NaN
97715   54969331          Beautiful private room in luxury building   NaN
97716   54969883                Heart of the West Village Apartment   NaN
97717   54970435              Brooklyn Style Hostel Private Room #5   NaN
97718   54970987  Cosy & Clean studio apt in the heart of Manhattan   NaN
97719   54971540           Grand 2 bed Apartment in Heart of Harlem   NaN
97720   54972092                      Large studio apt in Grammercy   NaN
97721   54972644                      Loft Style Bushwick Apartment   NaN
97722   54973197     Wyndham Midtown 45 (2 Bedroom Presidential) 7A   NaN
97723   54973749           New York home ferry ride from Manhattan.   NaN
97770   54999707                         Shared room with bunk beds   NaN
97771   55000259          Shared room with bunk beds in Bensonhurst   NaN
97772   55000812               Two bedrooms apt. in Jamaica Estates   NaN
97773   55001364           Quiet and modern Williamsburg garden 1BR   NaN
97774   55001916       Upper East Side creative sanctuary apartment   NaN
97775   55002469      Studio at Upper East Side Manhattan, New York   NaN
97776   55003021                               Spacious Harlem Room   NaN
97777   55003573                                 Flatiron Penthouse   NaN
97778   55004125                               New York Condominium   NaN
102045  57360790        Private Bedroom in Rego Park / Forest Hills   NaN
102046  57361342             Sunny budget friendly room in Bushwick   NaN
102047  57361894            Cozy Apartment on Bedford Ave, Brooklyn   NaN
102048  57362446                Your 1 bedroom home away from home!   NaN
102049  57362999  MASTER Cozy Bedroom Queen size 2 blocks Timesq...   NaN
102050  57363551        Sunny Brownstone Studio in BedStuy Brooklyn   NaN

In [45]:
nmd['id'].isna().sum() # so there are 0 null values to it!

0

In [46]:
nmd['host name'].isna().sum()

406

In [46]:
# Create a dictionary of column names and their duplicate counts
dup_summary = {col: nmd.duplicated(subset=[col]).sum() for col in nmd.columns}

# Filter out columns that have 0 duplicates for a cleaner list
only_dupes = {k: v for k, v in dup_summary.items() if v > 0}

print("Columns with duplicates and their counts:")
print(only_dupes)

Columns with duplicates and their counts:
{'id': 541, 'name': 41317, 'host id': 542, 'host_identity_verified': 102596, 'host name': 89408, 'neighbourhood group': 102591, 'neighbourhood': 102374, 'lat': 80607, 'long': 84824, 'country': 102597, 'country code': 102597, 'instant_bookable': 102596, 'cancellation_policy': 102595, 'room type': 102595, 'construction year': 102578, 'price': 101447, 'service fee': 102367, 'minimum nights': 102445, 'number of reviews': 102122, 'last review': 100121, 'reviews per month': 101582, 'review rate number': 102593, 'calculated host listings count': 102520, 'availability 365': 102160, 'house_rules': 100622}

So we have 541 duplicates in ID, host_id +id +1,

now we'll clean the id and host id!

In [47]:
# Save the dataframe to a file named 'results.csv'
nmd.to_csv('cleaned1.csv', index=False)